version: '3'
services:
  map-downloader:
    container_name: map-downloader
    image: tobara8/map-tiles-downloader
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./output:/app/output